### ISSUE TITLE
AutoComplete Doesn't work

### ISSUE THREAD

**Issue by wassimseif** [eddiekaiger/SwiftyAttributes#11]
Xcode can't autocomplete when i'm typing something like this 
```
  static let boldWithRedColor : [SwiftyAttributes.Attribute]! = [
        .font(UIFont.boldSystemFont(ofSize: 14))
        .textColor(UIColor.red)
    ]
```

Anyone has a fix for it ?

**Comment by eddiekaiger** [comment]
I've seen this happen with static variables sometimes in Xcode, it's not unique to `SwiftyAttributes`. Perhaps try using syntax like `static let boldWithRed = [Attribute.textColor(.red), .font(.boldSystemFont(ofSize: 14))`. Also might want to try doing a Clean in Xcode.
