### ISSUE TITLE
Does not work in xcode 9 beta

### ISSUE THREAD

**Issue by phiren** [eddiekaiger/SwiftyAttributes#13]
It does not work in xcode 9 beta, gives error, please check attached images
![error 1](https://user-images.githubusercontent.com/8377260/26918108-42ffd992-4c4e-11e7-915b-43f0e12b7d4b.png)
![error 2](https://user-images.githubusercontent.com/8377260/26918110-437260a2-4c4e-11e7-9a7f-98b362698b7e.png)

**Comment by eddiekaiger** [comment]
Just pushed up a `swift-4` branch. Please use that in the meantime, as it will be updated along with the Swift 4 and Xcode 9 betas :)
