### ISSUE TITLE
.withAttributes not working - xcode 9 beta issue

### ISSUE THREAD

**Issue by phiren** [eddiekaiger/SwiftyAttributes#14]
Somehow .withAttributes don't work in xcode 9 beta after using swift 4 repository

![screen shot 2017-06-09 at 12 06 57 pm](https://user-images.githubusercontent.com/8377260/26963898-abc36e44-4d0c-11e7-928b-baa01217800a.png)

**Comment by eddiekaiger** [comment]
Do you have `import SwiftyAttributes`? It works for me on Xcode 9 beta.

**Comment by phiren** [comment]
That was different problem, I was adding those files only to the Mac application but somehow that those files not added to compile sources, however still facing more problems with those files.

I have tried to download swift 4 repository and run in xcode 9 beta with mac application target, it throws below error:

> CompileSwift normal x86_64 /Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2/ExampleApp-macOS/AppDelegate.swift
>     cd /Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2
>     /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c "/Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2/ExampleApp-macOS/ViewController.swift" -primary-file "/Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2/ExampleApp-macOS/AppDelegate.swift" -target x86_64-apple-macosx10.11 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug -F /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug -enable-testing -g -module-cache-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/ModuleCache -swift-version 3 -D DEBUG -serialize-debugging-options -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-generated-files.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-own-target-headers.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-project-headers.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug/include -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/DerivedSources/x86_64 -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/DerivedSources -Xcc -DDEBUG=1 -Xcc "-working-directory/Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2" -emit-module-doc-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate~partial.swiftdoc -serialize-diagnostics-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.dia -Onone -module-name ExampleApp_macOS -emit-module-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate~partial.swiftmodule -emit-dependencies-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.d -emit-reference-dependencies-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.swiftdeps -o /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.o -index-store-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Index/DataStore -index-system-modules
> 
> <unknown>:0: error: fatal error encountered while reading from module 'SwiftyAttributes'; please file a bug report with your project and the crash log
> <unknown>:0: note: compiling as Swift 3.2, with 'SwiftyAttributes' built as Swift 4.0 (this is supported but may expose additional compiler issues)
> 
> *** DESERIALIZATION FAILURE (please include this section in any bug report) ***
> declaration is not a nominal type
> Cross-reference to module 'Foundation'
> ... NSAttributedStringKey
> 
> 0  swift                    0x000000010830c3aa PrintStackTraceSignalHandler(void*) + 42
> 1  swift                    0x000000010830b7e6 SignalHandler(int) + 662
> 2  libsystem_platform.dylib 0x00007fffc8db9b3a _sigtramp + 26
> 3  libsystem_platform.dylib 0x00007fff5af907e0 _sigtramp + 2451401920
> 4  libsystem_c.dylib        0x00007fffc8c3e420 abort + 129
> 5  swift                    0x0000000105a22ea1 swift::ModuleFile::fatal(llvm::Error) + 1569
> 6  swift                    0x0000000105a2e4f4 swift::ModuleFile::readGenericRequirements(llvm::SmallVectorImpl<swift::Requirement>&, llvm::BitstreamCursor&) + 1236
> 7  swift                    0x0000000105a2f48c swift::ModuleFile::getGenericSignatureOrEnvironment(llvm::PointerEmbeddedInt<unsigned int, 31>, bool) + 844
> 8  swift                    0x0000000105a27ef7 swift::ModuleFile::getDeclChecked(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 19351
> 9  swift                    0x0000000105a23324 swift::ModuleFile::getDecl(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 84
> 10 swift                    0x0000000105abfc65 swift::SerializedModuleLoader::loadExtensions(swift::NominalTypeDecl*, unsigned int) + 1573
> 11 swift                    0x0000000105e6bd3f swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 1631
> 12 swift                    0x0000000105e6b7d7 swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver*) + 247
> 13 swift                    0x0000000105e6fa51 swift::ConformanceLookupTable::lookupConformance(swift::ModuleDecl*, swift::NominalTypeDecl*, swift::ProtocolDecl*, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ProtocolConformance*>&) + 49
> 14 swift                    0x0000000105ecd300 swift::ModuleDecl::lookupConformance(swift::Type, swift::ProtocolDecl*, swift::LazyResolver*) + 1248
> 15 swift                    0x0000000105dff130 swift::ASTContext::getForeignRepresentationInfo(swift::NominalTypeDecl*, swift::ForeignLanguage, swift::DeclContext const*) + 5232
> 16 swift                    0x0000000105efcaa9 getForeignRepresentable(swift::Type, swift::ForeignLanguage, swift::DeclContext const*) + 1289
> 17 swift                    0x00000001059a0d3d swift::Lowering::TypeConverter::getLoweredCBridgedType(swift::Lowering::AbstractionPattern, swift::Type, bool, bool) + 1021
> 18 swift                    0x00000001059a0088 swift::Lowering::TypeConverter::getLoweredBridgedType(swift::Lowering::AbstractionPattern, swift::Type, swift::SILFunctionTypeRepresentation, swift::Lowering::TypeConverter::BridgedTypePurpose) + 392
> 19 swift                    0x000000010599fd3c swift::Lowering::TypeConverter::getBridgedInputType(swift::SILFunctionTypeRepresentation, swift::Lowering::AbstractionPattern, swift::CanType) + 556
> 20 swift                    0x00000001059bce12 swift::Lowering::TypeConverter::getLoweredASTFunctionType(swift::CanTypeWrapper<swift::AnyFunctionType>, unsigned int, swift::AnyFunctionType::ExtInfo, llvm::Optional<swift::SILDeclRef>) + 1266
> 21 swift                    0x00000001059c0888 swift::Lowering::TypeConverter::getConstantInfo(swift::SILDeclRef) + 2728
> 22 swift                    0x0000000104e0a254 getObjCMethodType(swift::irgen::IRGenModule&, swift::AbstractFunctionDecl*) + 100
> 23 swift                    0x0000000104e0a33a swift::irgen::emitObjCMethodDescriptorParts(swift::irgen::IRGenModule&, swift::AbstractFunctionDecl*, bool, bool, llvm::Constant*&, llvm::Constant*&, llvm::Constant*&) + 218
> 24 swift                    0x0000000104d63b62 (anonymous namespace)::ClassDataBuilder::buildMethodList(llvm::ArrayRef<(anonymous namespace)::ClassDataBuilder::MethodDescriptor>, llvm::StringRef) + 866
> 25 swift                    0x0000000104d6890d swift::irgen::emitObjCProtocolData(swift::irgen::IRGenModule&, swift::ProtocolDecl*) + 1725
> 26 swift                    0x0000000104e08b7f swift::irgen::IRGenModule::emitLazyObjCProtocolDefinitions() + 63
> 27 swift                    0x0000000104e66ce0 swift::irgen::IRGenModule::finalize() + 336
> 28 swift                    0x0000000104e4fbcd performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, llvm::GlobalVariable**, unsigned int) + 2765
> 29 swift                    0x0000000104cdec4b performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 16603
> 30 swift                    0x0000000104cd9304 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7332
> 31 swift                    0x0000000104c8f728 main + 12248
> 32 libdyld.dylib            0x00007fffc8baa235 start + 1
> 33 libdyld.dylib            0x0000000000000046 start + 927292946
> Stack dump:
> 0.	Program arguments: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2/ExampleApp-macOS/ViewController.swift -primary-file /Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2/ExampleApp-macOS/AppDelegate.swift -target x86_64-apple-macosx10.11 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug -F /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug -enable-testing -g -module-cache-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/ModuleCache -swift-version 3 -D DEBUG -serialize-debugging-options -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-generated-files.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-own-target-headers.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/ExampleApp-macOS-project-headers.hmap -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug/include -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/DerivedSources/x86_64 -Xcc -I/Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/iphone-4/Downloads/SwiftyAttributes-swift-4 2 -emit-module-doc-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate~partial.swiftdoc -serialize-diagnostics-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.dia -Onone -module-name ExampleApp_macOS -emit-module-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate~partial.swiftmodule -emit-dependencies-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.d -emit-reference-dependencies-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.swiftdeps -o /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Intermediates.noindex/SwiftyAttributes.build/Debug/ExampleApp-macOS.build/Objects-normal/x86_64/AppDelegate.o -index-store-path /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Index/DataStore -index-system-modules 
> 1.	While reading from /Users/iphone-4/Library/Developer/Xcode/DerivedData/SwiftyAttributes-foecanpptsugxehkefleooscivts/Build/Products/Debug/SwiftyAttributes.framework/Modules/SwiftyAttributes.swiftmodule/x86_64.swiftmodule
> 2.	While deserializing extension of '<null>' (ExtensionDecl #60) in 'SwiftyAttributes'

**Comment by eddiekaiger** [comment]
Are you still having this issue? I can't seem to reproduce anything similar.

**Comment by phiren** [comment]
I stoped using beta xcode for now, will test later. Are you testing in mac application?

**Comment by linqingmo** [comment]
I solve the problem.
Swift version of SwiftyAttributes.framework is 4.0, while ExampleApp-iOS is 3.2. Change to 4.0 then it works.
