### ISSUE TITLE
Collision with Foundation:  `NSAttributedString`'s `enumerateAttributes` method

### ISSUE THREAD

**Issue by zachlucas** [eddiekaiger/SwiftyAttributes#18]
I'm getting a collision with Foundation with the `NSAttributedString` method `enumerateAttributes`:
```
Ambiguous reference to member 'enumerateAttribute(_:in:options:using:)'
```

**Comment by eddiekaiger** [comment]
what does your closure look like? I've found that you can disambiguate it by being more specific with the closure parameters.

**Comment by eddiekaiger** [comment]
Actually, I'm going to rename them: #19

**Comment by eddiekaiger** [comment]
[v4.1.0](https://github.com/eddiekaiger/SwiftyAttributes/releases/tag/v4.1.0) is live! Thanks for creating the issue @zachlucas .
