### ISSUE TITLE
Get color of underlined text

### ISSUE THREAD

**Issue by popo63301** [eddiekaiger/SwiftyAttributes#20]
Hello

I'm using this library on macOS with Swift for a project. So, basically, I want to get the color of the underlined text in my NSTextStorage of my NSTextView. This library is very good to create attributes, modify and even delete, but I wonder how to access the color. 

Thanks any advance for your ideas. 😄

**Comment by eddiekaiger** [comment]
So perhaps something like this?

```swift
if case let .underlineColor(color)? = storage.swiftyAttribute(.underlineColor, at: 2) {
    print(color)
}
```

This is *SwiftyAttributes v4.1.0* (the latest), the method was previously just called `attribute(_:at:)`.

**Comment by popo63301** [comment]
It works also for the old version, here I use it to know if the 6th char is red underlined: 
```

if case let .underlineColor(color)? = storage.attribute(.underlineColor, at: 6) {
    var red = NSColor.red
    print(color == red)
} 
```

Thanks a lot !!!!
