### ISSUE TITLE
Readme code not working

### ISSUE THREAD

**Issue by byroncoetsee** [eddiekaiger/SwiftyAttributes#22]
Hi there,

The following line, copy pasted, doesn't seem to work. Swift 4.

`let fancyString = "Hello".withFont(.systemFont(ofSize: 12)) + " World!".withFont(.systemFont(ofSize: 18))`

Error is:

`Binary operator '+' cannot be applied to two 'NSMutableAttributedString' operands`

**Comment by eddiekaiger** [comment]
try adding `import SwiftyAttributes` at the top?
