### ISSUE TITLE
Use of unresolved identifier 'SpellingState' on macOS

### ISSUE THREAD

**Issue by Schaefers** [eddiekaiger/SwiftyAttributes#23]
Installed via cocoa pods, got the error above. 

Disappeared after adding 
`public typealias SpellingState = NSAttributedString.SpellingState` in Attribute.swift:L15.

**Comment by eddiekaiger** [comment]
are you on Swift 4 or Swift 3.x?

**Comment by eddiekaiger** [comment]
`SpellingState` is an enum found [here](https://github.com/eddiekaiger/SwiftyAttributes/blob/master/SwiftyAttributes/Sources/macOS/SpellingState.swift). Are you sure you're on the latest? (v4.1.0)

**Comment by Schaefers** [comment]
I’m on Swift 4. Yeah, just added the pod without version specifier.
