### ISSUE TITLE
Unified prefix for all wrappers

### ISSUE THREAD

**Issue by RomanPodymov** [eddiekaiger/SwiftyAttributes#36]
Hello.
I found out that currently in **SwiftyAttributes** there are different prefixes for the Swift Standard Library properties and functions wrappers. For example, `UINavigationBar.swiftyTitleTextAttributes` starts with `swifty` and `NSString.swifty_size(withSwiftyAttributes:)` starts with `swifty_`. Would you like to unify these prefixes? For example, I can rename `NSString.swifty_size(withSwiftyAttributes:)` to `NSString.swiftySize(withSwiftyAttributes:)`.

**Comment by eddiekaiger** [comment]
Yeah let's do that! Thanks 🙏
