### ISSUE TITLE
iOS 13设备出现的问题

### ISSUE THREAD

**Issue by FunnyFzl** [eddiekaiger/SwiftyAttributes#41]
CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].

**Comment by RomanPodymov** [comment]
Hello @FunnyFzl 
How can we solve your problem with SwiftyAttributes? Or should we close the issue?

**Comment by FunnyFzl** [comment]
> Hello @FunnyFzl
> How can we solve your problem? Or should we close the issue?

I don't know how to solve
