### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by Drusy** [eddiekaiger/SwiftyAttributes#42]
Since Xcode 11 includes Swift Package natively, it would be nice to be able to include SwiftyAttributes using SPM !

**Comment by eddiekaiger** [comment]
That's true. I'll try to post a PR in the coming week!

**Comment by kenji21** [comment]
seems that a release is needed to have SPM being able to resolve it:

![Screenshot 1](https://user-images.githubusercontent.com/1105089/82047779-b3518d00-96b3-11ea-9c80-372930b28d6f.png)

**Comment by eddiekaiger** [comment]
Released 5.2.0! https://github.com/eddiekaiger/SwiftyAttributes/releases/tag/v5.2.0
