### ISSUE TITLE
Is it possible to make the floating placeholder text in Capitalized or lower case?

### ISSUE THREAD

**Issue by hassan31** [eddiekaiger/SwiftyAttributes#45]
Hi,

I'm wondering if it is possible to change the case of floating placeholder text.

Thanks,
Hassan

**Comment by eddiekaiger** [comment]
Hi @hassan31, which placeholder text are you referring to?

**Comment by hassan31** [comment]
@eddiekaiger ah, sorry, I've commented at wrong place. Sorry for that.
