### ISSUE TITLE
Update support for Swift Package Manager

### ISSUE THREAD

**Issue by thejeff77** [eddiekaiger/SwiftyAttributes#46]
Would you be willing to add support for swift package manager?

**Comment by thejeff77** [comment]
Oops.. looks like this is done. Just needs to be added to the README

**Comment by thejeff77** [comment]
And has issues with newer swift libs:

Showing All Messages
: https://github.com/eddiekaiger/SwiftyAttributes.git has no Package.swift manifest for version 5.1.1

**Comment by RomanPodymov** [comment]
Hello @thejeff77 
Can you still reproduce the issue? If so, can you provide us more details?

**Comment by thejeff77** [comment]
It sounds like you want more information, what information do you think is missing from this report? 

It also sounds that you think this issue is resolved. What have you done to resolve this issue?  How many times did you attempt to reproduce the issue before resolving or commenting on this defect report?

**Comment by eddiekaiger** [comment]
Added to README: https://github.com/eddiekaiger/SwiftyAttributes#installation

Tested and it works.
