### ISSUE TITLE
Update Target Version to 9.0

### ISSUE THREAD

**Issue by thejeff77** [eddiekaiger/SwiftyAttributes#50]
Build warning is always there:

/Users/jeffreyblayney/Library/Developer/Xcode/DerivedData/PracticePlayer-bcsqogsyamkqalgkuggzxalocanz/SourcePackages/checkouts/SwiftyAttributes/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99.

Should update deployment target to 9.0 so this goes away.

**Comment by eddiekaiger** [comment]
Resolved with #51
