### ISSUE TITLE
In iOS12, 13, the withTextColor does not display text immediately

### ISSUE THREAD

**Issue by jaeeunlee322** [eddiekaiger/SwiftyAttributes#55]
Hello. 😄  I have a problem in iOS 12, 13.
It is normal for versions iOS 14 and above.
The first time I open the screen with the NSMutableAttributedString, the `withTextColor()` does not apply.
And i also have a problem in `withAttributes([.textColor()]`.
When I scroll through the screen with the NSMutableAttributedString and come back, the text color will appear as I wish.
I'd like to know a solution.

**Comment by metatron1973** [comment]
![image](https://user-images.githubusercontent.com/80199202/175832187-8bab7088-4ad7-46b9-9a60-49d74e01c3c7.png) any chance this all ties into the fraud over at instacart and that Wilson rating system you might want to look at that part

**Comment by metatron1973** [comment]
![image](https://user-images.githubusercontent.com/80199202/175832187-8bab7088-4ad7-46b9-9a60-49d74e01c3c7.png) any chance this all ties into the fraud over at instacart and that Wilson rating system you might want to look at that part

**Comment by eddiekaiger** [comment]
This library is basically just syntactic sugar for `NSAttributedString`. An issue like the one you described is likely due to a bug within the OS or in the client.
