### ISSUE TITLE
Change link color?

### ISSUE THREAD

**Issue by sergeymild** [eddiekaiger/SwiftyAttributes#59]
Hi, thanks for great library, but i have a problem i can't change ink color it is always default blue.
even if i make like with
```
attributedString += text.withLink(.init(string: destination)!)
                                .withFont(.boldSystemFont(ofSize: 15))
                                .withTextColor(.green)
```

it has no effect

**Comment by eddiekaiger** [comment]
@sergeymild I believe that's done on the textView itself via `linkTextAttributes`, like so:

```swift
textView.linkTextAttributes = [Attribute.textColor(.red)].foundationAttributes
```

**Comment by sergeymild** [comment]
Yes it's works thanks
