### ISSUE TITLE
AttributedString+SwiftyAttributes.swift:95:29: Generic parameter 'Element' could not be inferred

### ISSUE THREAD

**Issue by kohdesmond** [eddiekaiger/SwiftyAttributes#8]
Hi Eddie,

I got this error when i wanna compile the app.

Pods/SwiftyAttributes/SwiftyAttributes/Sources/common/NSAttributedString+SwiftyAttributes.swift:95:29: Generic parameter 'Element' could not be inferred

**Comment by eddiekaiger** [comment]
Which version of `SwiftyAttributes` are you on?

**Comment by kohdesmond** [comment]
@eddiekaiger the lastest from pods

**Comment by eddiekaiger** [comment]
Hmm. Working fine for me. What version of Xcode are you on? Perhaps try doing a clean build or reinstalling that pod?

**Comment by kohdesmond** [comment]
hmm, weird it doesn't work for me after clearing and reinstalling.

pod showing:
Using SwiftyAttributes (3.1.0)

![screen shot 2017-01-18 at 09 31 19](https://cloud.githubusercontent.com/assets/1192544/22047311/33cf1a70-dd61-11e6-8b93-3b96ab138054.png)

**Comment by kohdesmond** [comment]
Also to note that i was prompted to convert to latest swift syntax.

**Comment by eddiekaiger** [comment]
You're probably using Swift 2.3 then? If you are, you should do `pod 'SwiftyAttributes', '1.1'`

**Comment by kohdesmond** [comment]
@eddiekaiger  nope i'm using Swift 3.

![screen shot 2017-01-18 at 13 41 21](https://cloud.githubusercontent.com/assets/1192544/22052211/dcdec120-dd83-11e6-95f1-818e7b442ab3.png)

**Comment by eddiekaiger** [comment]
Make sure your entire project is on Swift 3. Also, perhaps try forking it and see if this solves it:

```swift
let attributeRange: ([Attribute], Range<Int>) = (attributes, range)
attributeRanges.append(attributeRange)
````

**Comment by yasserislam** [comment]
same problem with me
i wrote:
```
            let attributeRange: ([Attribute], CountableRange<Int>) = (attributes, range as! CountableRange<Int>)
            attributeRanges.append(attributeRange)

```
is it correct ?

**Comment by eddiekaiger** [comment]
@yasserislam why is it a `CountableRange`? The example I have above (using `Range`) should fix it, although I'm still not quite sure why it's not compiling for you (works for me on Swift 3, Xcode 8.2). Could be some strange bug in Swift, so I'll update the pod soon.

**Comment by yasserislam** [comment]
@eddiekaiger I used `CountableRange` because that is the type of the return value: `[([Attribute], CountableRange<Int>)]`

we are waiting the update
thanks..

**Comment by eddiekaiger** [comment]
Ok @yasserislam @kohdesmond I just realized that `CountableRange` was used in an older version of this file that was a work in progress, but `v3.1.0` definitely has the correct, working code. Make sure you have the very latest by specifying `'SwiftyAttributes', '~> 3.1.0'`. It seems like you somehow have an older version of the repo. Might want to try `pod update SwiftyAttributes` if that doesn't work.
