### ISSUE TITLE
Binary operator '+' cannot be applied to two 'NSMutableAttributedString' operands

### ISSUE THREAD

**Issue by cyrille-legrand** [eddiekaiger/SwiftyAttributes#9]
While concatenating two attributed strings, just like in the readme : 

```
let fancyString = "Hello".withFont(.systemFont(ofSize: 12)) + " World!".withFont(.systemFont(ofSize: 18))
```

The compiler produces an error stating that "Binary operator '+' cannot be applied to two 'NSMutableAttributedString' operands", and `fancyString` shows as an `<<< Error type >>>`.

Swift 3, Xcode 8.2, SwiftyAttributes 3.1.0 with CocoaPods.

**Comment by eddiekaiger** [comment]
You sure you have `import SwiftyAttributes` at the top? This works fine for me on a fresh project in Swift 3, and tests are passing.

**Comment by cyrille-legrand** [comment]
Yup, that was it.

Strange that `.withFont(...)` and other functions work out-of-the-box without the `import`. That's what misguided me.

Please consider the issue a non-issue and close it.
